language: python

matrix:
  include:
    - python: 2.6
      env: TOXENV="py26,py26-color,cli"
    - python: 2.7
      env: TOXENV="copying,py27,py27-color,cli,coverage"

before_install:
  - pip install tox

install:
  - pip install .

script:
- tox